
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Windows 8.1
 */
public class Frame1 extends javax.swing.JFrame {
    String temp="";
    Double ti, bt, hi;
    
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ideal = new javax.swing.JTextField();
        Berat = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Hitung = new javax.swing.JButton();
        cblagi = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Tinggi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        saran = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Jenis Kelamin");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 190, 80, 20);

        jLabel3.setText("Berat Badan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 150, 80, 20);

        jLabel4.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 300, 170, 20);

        jLabel5.setText("cm");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 110, 30, 20);

        jLabel6.setText("Tinggi");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 110, 80, 20);
        getContentPane().add(ideal);
        ideal.setBounds(210, 300, 90, 20);
        getContentPane().add(Berat);
        Berat.setBounds(160, 150, 90, 30);
        getContentPane().add(Nama);
        Nama.setBounds(160, 70, 170, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Laki - Laki");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(260, 190, 100, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Perempuan");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(160, 190, 100, 23);

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        getContentPane().add(Hitung);
        Hitung.setBounds(30, 250, 90, 20);

        cblagi.setText("Coba Lagi");
        cblagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblagiActionPerformed(evt);
            }
        });
        getContentPane().add(cblagi);
        cblagi.setBounds(150, 250, 100, 20);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(283, 250, 80, 20);

        jLabel7.setText("kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 300, 30, 20);

        jLabel8.setText("Nama");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 70, 80, 20);
        getContentPane().add(Tinggi);
        Tinggi.setBounds(160, 110, 90, 30);

        jLabel9.setText("kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 150, 30, 20);

        jLabel10.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 20, 120, 30);

        jLabel11.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(120, 330, 150, 20);
        getContentPane().add(saran);
        saran.setBounds(20, 390, 360, 30);
        getContentPane().add(hasil);
        hasil.setBounds(20, 350, 360, 30);

        setBounds(0, 0, 416, 482);
    }// </editor-fold>//GEN-END:initComponents

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        if (Nama.getText().equals("")||Berat.getText().equals("")||
                Tinggi.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data masukkan harus diisi!");
        } else if(jRadioButton1.isSelected()||jRadioButton2.isSelected()){
        try{
            Proses();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Inputan salah");
        }
        }else{
            JOptionPane.showMessageDialog(null, "Radio Button harus dipilih");
        }
    }//GEN-LAST:event_HitungActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void cblagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblagiActionPerformed
        Nama.setText("");
        Tinggi.setText("");
        Berat.setText("");
        buttonGroup1.clearSelection();
        ideal.setText("");
        hasil.setText("");
        saran.setText("");
    }//GEN-LAST:event_cblagiActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Berat;
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Tinggi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cblagi;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField ideal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField saran;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.parseDouble(Tinggi.getText());
        bt = Double.parseDouble(Berat.getText());
        
        if(jRadioButton1.isSelected()){
            hi = (ti - 100) * 1;
        } else if(jRadioButton2.isSelected()){
            hi = (ti - 104) * 1;
        }
        temp = Double.toString(hi.intValue());
        
        if(hi < bt){
            ideal.setText(temp);
            hasil.setText("Maaf " + Nama.getText() + " , Sepertinya anda Overdosis");
            saran.setText("Banyaklah berolahraga dan hindari makanan berkolestrol");
        }else if(hi > bt){
            ideal.setText(temp);
            hasil.setText("Maaf " + Nama.getText() + " , Sepertinya anda Under");
            saran.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
        }else{
            ideal.setText(temp);
            hasil.setText("Hallo " + Nama.getText() + " , Berat badan anda sudah normal");
            saran.setText("Lanjutkan pola makan teratur dan gaya hidup sehat");
        }
    }
}
